export const CHAT_CREATE_REQUEST = "CHAT_CREATE_REQUEST";
export const CHAT_CREATE_SUCCESS = "CHAT_CREATE_SUCCESS";
export const CHAT_CREATE_FAIL = "CHAT_CREATE_FAIL";
export const CHAT_CREATE_RESET = "CHAT_CREATE_RESET";

export const CHAT_LIST_REQUEST = "CHAT_LIST_REQUEST";
export const CHAT_LIST_SUCCESS = "CHAT_LIST_SUCCESS";
export const CHAT_LIST_FAIL = "CHAT_LIST_FAIL";

export const CHAT_DETAILS_REQUEST = "CHAT_DETAILS_REQUEST";
export const CHAT_DETAILS_SUCCESS = "CHAT_DETAILS_SUCCESS";
export const CHAT_DETAILS_FAIL = "CHAT_DETAILS_FAIL";
export const CHAT_DETAILS_RESET = "CHAT_DETAILS_RESET";

export const CHAT_GROUP_NAME_UPDATE_REQUEST = "CHAT_GROUP_NAME_UPDATE_REQUEST";
export const CHAT_GROUP_NAME_UPDATE_SUCCESS = "CHAT_GROUP_NAME_UPDATE_SUCCESS";
export const CHAT_GROUP_NAME_UPDATE_FAIL = "CHAT_GROUP_NAME_UPDATE_FAIL";
export const CHAT_GROUP_NAME_UPDATE_RESET = "CHAT_GROUP_NAME_UPDATE_RESET";
