export const NOTIFICATION_LIST_REQUEST = "NOTIFICATION_LIST_REQUEST";
export const NOTIFICATION_LIST_SUCCESS = "NOTIFICATION_LIST_SUCCESS";
export const NOTIFICATION_LIST_FAIL = "NOTIFICATION_LIST_FAIL";

export const NOTIFICATION_OPEN_REQUEST = "NOTIFICATION_OPEN_REQUEST";
export const NOTIFICATION_OPEN_SUCCESS = "NOTIFICATION_OPEN_SUCCESS";
export const NOTIFICATION_OPEN_FAIL = "NOTIFICATION_OPEN_FAIL";

export const NOTIFICATION_OPEN_ALL_REQUEST = "NOTIFICATION_OPEN_ALL_REQUEST";
export const NOTIFICATION_OPEN_ALL_SUCCESS = "NOTIFICATION_OPEN_ALL_SUCCESS";
export const NOTIFICATION_OPEN_ALL_FAIL = "NOTIFICATION_OPEN_ALL_FAIL";

export const NOTIFICATION_LATEST_REQUEST = "NOTIFICATION_LATEST_REQUEST";
export const NOTIFICATION_LATEST_SUCCESS = "NOTIFICATION_LATEST_SUCCESS";
export const NOTIFICATION_LATEST_FAIL = "NOTIFICATION_LATEST_FAIL";
